#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <grtest_icons.h>

int32_t grtest_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm grtest!");

    return 0;
}
